[package]
name = "vault-system"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "20.5.0"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
soroban-sdk = { version = "20.5.0", features = ["testutils"] }
